/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/usr/local/Cellar/nim/0.17.2/nim/lib -o /Users/cloudspider/Desktop/pracNim/nimcache/fib.o /Users/cloudspider/Desktop/pracNim/nimcache/fib.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, fib_JGpuUVEjLEshEg9bCB5xVDg)(NI num);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, fibDatInit000)(void);

N_NIMCALL(NI, fib_JGpuUVEjLEshEg9bCB5xVDg)(NI num) {
	NI result;
	result = (NI)0;
	{
		if (!(num < ((NI) 2))) goto LA3_;
		result = num;
	}
	goto LA1_;
	LA3_: ;
	{
		NI T6_;
		NI T7_;
		T6_ = (NI)0;
		T6_ = fib_JGpuUVEjLEshEg9bCB5xVDg((NI)(num - ((NI) 1)));
		T7_ = (NI)0;
		T7_ = fib_JGpuUVEjLEshEg9bCB5xVDg((NI)(num - ((NI) 2)));
		result = (NI)(T6_ + T7_);
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	fibDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NI T1_;
	NimStringDesc* T2_;
	T1_ = (NI)0;
	T1_ = fib_JGpuUVEjLEshEg9bCB5xVDg(((NI) 45));
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(T1_);
	printf("%s\012", T2_? (T2_)->data:"nil");
	fflush(stdout);
}

NIM_EXTERNC N_NOINLINE(void, fibDatInit000)(void) {
}

